### ISSUE TITLE
how to generate icosphere pkl for different orders of icos

### ISSUE THREAD

**Issue by ChunCun** [ngohgia/brain-surf-cnn#1]
Hi, awesome work! I am wondering if you could share codes to generate those pkl files for different orders of icos. Thanks.

**Comment by sahahn** [comment]
Seems like they are generated based off code from https://github.com/maxjiang93/ugscnn

**Comment by ngohgia** [comment]
sorry for the super late update. You can find the instruction to generate those assets here https://github.com/ngohgia/brain-surf-cnn/tree/master/data/fs_LR_mesh_templates/scripts
