### ISSUE TITLE
Batch Size

### ISSUE THREAD

**Issue by eminSerin** [ngohgia/brain-surf-cnn#4]
Hi again! 

Thanks a lot again for the great architecture! I have a stupid question regarding the batch size. 

https://github.com/ngohgia/brain-surf-cnn/blob/4d2c9fc661e6ec50cbe6e699ea02c0e66d41b14f/utils/parser.py#L100

I wonder why the BrainSurfCNN does only support the batch size of 2 now. Is that because the model allocates high memory due to the computation below: 

https://github.com/ngohgia/brain-surf-cnn/blob/4d2c9fc661e6ec50cbe6e699ea02c0e66d41b14f/model/brain_surf_cnn.py#L147

or, is there are any other particular reasons? Do you think it is okay to use a batch size of 1? 

Thanks a lot!

**Comment by ngohgia** [comment]
Hi Emin. There are 2 reasons for the batch size of 2:
1) Yes, the memory required for the model is high so batch size > 2 may not work on some GPUs
2) For training with MSE loss, batch size of 1 is okay. But if you want to try the RC loss, it needs at least batch size of 2 to compute same-subject and across-subject error, i.e. at least 2 subjects are needed to compute across-subject error, hence the batch size of at least 2

**Comment by eminSerin** [comment]
Thanks a lot for your helpful answers!
